### ISSUE TITLE
Web App: UI Styling for Survey Form

### ISSUE THREAD

**Issue by YolineB** [specollective/insights-agent-web-app#41]
[Survey Form Desktop](https://www.figma.com/file/saSl8LVUCEYpptPsvyGGHq/Insights-Agent?node-id=906%3A413&t=ZGen6fVB8lCeBm30-0) and [Survey Form Mobile ](https://www.figma.com/file/saSl8LVUCEYpptPsvyGGHq/Insights-Agent?node-id=906%3A4263&t=ZGen6fVB8lCeBm30-0)

<img width="300" alt="image" src="https://user-images.githubusercontent.com/92892101/204615069-b083b541-a368-4c15-b813-8c4218833c28.png">

- [ ] Background for info survey should be #AECA9B
- [ ] Radius 5px

<img width="206" alt="image" src="https://user-images.githubusercontent.com/92892101/204616163-100f8b79-f041-408b-8e66-8f76e81cd0d5.png">

- [ ] Submit button background should be #37770D
- [ ] Radius 5px
- [ ] White font color
- [ ] Pointer cursor for clear form

**Comment by najwanan** [comment]
Adding styling for breakpoint w768, medium devices to widen survey appropriately 
<img width="812" alt="image" src="https://user-images.githubusercontent.com/66931010/205955815-39a10938-2e71-4d20-a479-680e5721ae9b.png">
