### ISSUE TITLE
Web App: UI styling for Download Page

### ISSUE THREAD

**Issue by YolineB** [specollective/insights-agent-web-app#48]
[Figma design for desktop ](https://www.figma.com/file/saSl8LVUCEYpptPsvyGGHq/Insights-Agent?node-id=925%3A1095&t=vGDaOjtkl6UErvmO-0)

[Figma design for mobile](https://www.figma.com/file/saSl8LVUCEYpptPsvyGGHq/Insights-Agent?node-id=952%3A981&t=vGDaOjtkl6UErvmO-0)

- [ ] Download button, #37770D background, black border, 10px radius
- [ ] Set Up Instructions
- [ ] Icon

Desktop:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/92892101/204635134-a595ea96-47f7-4cf4-94cc-5c6ef7a4c8ca.png">

Mobile:
<img width="267" alt="image" src="https://user-images.githubusercontent.com/92892101/204635289-5245b5fe-06e9-4ccd-b91d-4d5cc8b14602.png">

**Comment by najwanan** [comment]
@dashcraft 
The current code pulls in instructions for uninstall directions which are not included on the Figma wireframe.
Question:
Do we need to include uninstall directions?
If so, then is the following the correct approach?
- create a separate component in the elements folder named UninstallInstructions
- put a placeholder for the text
<img width="1094" alt="Screenshot 2022-12-02 at 11 16 44 AM" src="https://user-images.githubusercontent.com/66931010/205369971-65c2dc28-7ae9-4750-8de0-feee1829cab5.png">

**Comment by najwanan** [comment]
Last detail to fix is the weight and size of the numbers in the ol. Couldn't find any docs that helped. Any suggestions as to how best to approach this?
<img width="712" alt="Screenshot 2022-12-02 at 2 36 01 PM" src="https://user-images.githubusercontent.com/66931010/205401624-a4e22c67-41f3-4e36-9dc0-73aff6007a36.png">
<img width="435" alt="Screenshot 2022-12-02 at 2 37 31 PM" src="https://user-images.githubusercontent.com/66931010/205401653-b41a8ce8-9267-470e-b10d-e6f2b86404e7.png">

**Comment by dashcraft** [comment]
1. Go ahead and copy the text over, that's fine
2. For the ordered list, this should help you style them: https://stackoverflow.com/questions/21369843/is-there-a-way-to-make-numbers-in-an-ordered-list-bold
