### ISSUE TITLE
Web App: Change help contact to only email

### ISSUE THREAD

**Issue by YolineB** [specollective/insights-agent-web-app#73]
Any references to contact BuildJustly for help should only have the help@insightsagent.com email listed. All phone number stand ins should be removed. 

Currently listed on the following pages:

- [x] [Participant Feedback Page](https://www.figma.com/file/saSl8LVUCEYpptPsvyGGHq/Insights-Agent?node-id=925%3A947&t=ZN9zf5IZbZLkdhzG-0)
- [x] [Download instructions page](https://www.figma.com/file/saSl8LVUCEYpptPsvyGGHq/Insights-Agent?node-id=925%3A1095&t=ZN9zf5IZbZLkdhzG-0)

#### Before:
![Screenshot 2022-12-15 at 12 08 24 PM](https://user-images.githubusercontent.com/59852686/207936328-7da13afb-35ed-45d3-b39f-7d3463510ecc.png)
![Screenshot 2022-12-15 at 12 09 46 PM](https://user-images.githubusercontent.com/59852686/207936346-6af70e0e-6374-4b43-b3b6-ed65fd1f1560.png)

#### After:
![Screenshot 2022-12-15 at 12 37 59 PM](https://user-images.githubusercontent.com/59852686/207941145-09f1258f-b1bd-49f3-af12-bbfebdefce3c.png)
![Screenshot 2022-12-15 at 12 38 14 PM](https://user-images.githubusercontent.com/59852686/207941149-2dcc72d8-faa3-4d23-9bb0-659301ea600c.png)

**Comment by Saige243** [comment]
Fixed in #79
